
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, Scrollbar, RIGHT, Y, END, BOTTOM


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\LENOVO\Documents\TKinter Projects\build\assets\frame0")

calculation = ""
result = ""

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def add_symbol(symbol):
    global calculation
    calculation += str(symbol)
    misc_entry_calculation.config(fg = "#FFFFFF")
    misc_entry_calculation.delete(1.0, "end")
    misc_entry_calculation.insert(1.0, calculation)

def delete_symbol():
    global calculation
    calculation = calculation[:-1]
    misc_entry_calculation.config(fg = "#FFFFFF")
    misc_entry_calculation.delete(1.0, "end")
    misc_entry_calculation.insert(1.0, calculation)

def evaluate_calculation():
    global calculation
    global result
    try:
        result = str(eval(calculation))
        canvas.itemconfig(canvas_text, text = result)
        misc_entry_calculation.config(fg = "#a2bbcf")
        result = ""
        calculation = ""
    except:
        clear_field()
        misc_entry_calculation.insert(1.0, "Error")

def clear_field():
    global calculation
    calculation = ""
    misc_entry_calculation.delete(1.0, "end")
    misc_entry_calculation.config(fg = "#FFFFFF")
    canvas.itemconfig(canvas_text, text = 0)


window = Tk()
window.geometry("634x450")
window.title("Simple Calculator")
window.configure(bg = "#142F44")


canvas = Canvas(
    window,
    bg = "#142F44",
    height = 450,
    width = 634,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)

img_calculation_entry = PhotoImage(
    file=relative_to_assets("calculation_entry.png"))

img_num_button = PhotoImage(
    file=relative_to_assets("num_button.png"))
img_num_button_hover = PhotoImage(
    file=relative_to_assets("num_button_hover.png"))

img_op_button = PhotoImage(
    file=relative_to_assets("op_button.png"))

img_del_button = PhotoImage(
    file=relative_to_assets("del_button.png"))
img_del_button_hover = PhotoImage(
    file=relative_to_assets("del_button_hover.png"))
img_del_button_press = PhotoImage(
    file=relative_to_assets("del_button_press.png"))

img_res_button = PhotoImage(
    file=relative_to_assets("res_button.png"))
img_res_button_hover = PhotoImage(
    file=relative_to_assets("res_button_hover.png"))
img_res_button_press = PhotoImage(
    file=relative_to_assets("res_button_press.png"))

img_clr_button = PhotoImage(
    file=relative_to_assets("clr_button.png"))
img_clr_button_hover = PhotoImage(
    file=relative_to_assets("clr_button_hover.png"))
img_clr_button_press = PhotoImage(
    file=relative_to_assets("clr_button_press.png"))

img_result_bar = PhotoImage(
    file=relative_to_assets("result_bar.png"))
image_1 = canvas.create_image(
    175.0,
    27.0,
    image=img_result_bar
)

global_font = "Arial"
global_font_size = 32

canvas_text = canvas.create_text(
    11.0,
    5.0,
    anchor="nw",
    text="0",
    fill="#FFFFFF",
    font=(global_font, global_font_size * -1)
)

num_button_1 = Button(
    text="1",
    fg = "#FFFFFF",
    activeforeground="#FFFFFF",
    compound="center",
    font=(global_font, global_font_size * -1),
    image=img_num_button,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: add_symbol(1),
    relief="flat"
)
num_button_1.place(
    x=5.0,
    y=306.0,
    width=82.92682647705078,
    height=45.0
)

num_button_2 = Button(
    text="2",
    fg = "#FFFFFF",
    activeforeground="#FFFFFF",
    compound="center",
    font=(global_font, global_font_size * -1),
    image=img_num_button,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: add_symbol(2),
    relief="flat"
)
num_button_2.place(
    x=90.6910629272461,
    y=306.0,
    width=82.92682647705078,
    height=45.0
)

num_button_3 = Button(
    text="3",
    fg = "#FFFFFF",
    activeforeground="#FFFFFF",
    compound="center",
    font=(global_font, global_font_size * -1),
    image=img_num_button,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: add_symbol(3),
    relief="flat"
)
num_button_3.place(
    x=176.3821258544922,
    y=306.0,
    width=82.92682647705078,
    height=45.0
)

num_button_4 = Button(
    text="4",
    fg = "#FFFFFF",
    activeforeground="#FFFFFF",
    compound="center",
    font=(global_font, global_font_size * -1),
    image=img_num_button,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: add_symbol(4),
    relief="flat"
)
num_button_4.place(
    x=5.0,
    y=259.0,
    width=82.92682647705078,
    height=45.0
)

num_button_5 = Button(
    text="5",
    fg = "#FFFFFF",
    activeforeground="#FFFFFF",
    compound="center",
    font=(global_font, global_font_size * -1),
    image=img_num_button,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: add_symbol(5),
    relief="flat"
)
num_button_5.place(
    x=90.6910629272461,
    y=259.0,
    width=82.92682647705078,
    height=45.0
)

num_button_6 = Button(
    text="6",
    fg = "#FFFFFF",
    activeforeground="#FFFFFF",
    compound="center",
    font=(global_font, global_font_size * -1),
    image=img_num_button,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: add_symbol(6),
    relief="flat"
)
num_button_6.place(
    x=176.3821258544922,
    y=259.0,
    width=82.92682647705078,
    height=45.0
)

num_button_7 = Button(
    text="7",
    fg = "#FFFFFF",
    activeforeground="#FFFFFF",
    compound="center",
    font=(global_font, global_font_size * -1),
    image=img_num_button,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: add_symbol(7),
    relief="flat"
)
num_button_7.place(
    x=5.0,
    y=212.0,
    width=82.92682647705078,
    height=45.0
)

num_button_8 = Button(
    text="8",
    fg = "#FFFFFF",
    activeforeground="#FFFFFF",
    compound="center",
    font=(global_font, global_font_size * -1),
    image=img_num_button,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: add_symbol(8),
    relief="flat"
)
num_button_8.place(
    x=90.6910629272461,
    y=212.0,
    width=82.92682647705078,
    height=45.0
)

num_button_9 = Button(
    text="9",
    fg = "#FFFFFF",
    activeforeground="#FFFFFF",
    compound="center",
    font=(global_font, global_font_size * -1),
    image=img_num_button,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: add_symbol(9),
    relief="flat"
)
num_button_9.place(
    x=176.3821258544922,
    y=212.0,
    width=82.92682647705078,
    height=45.0
)

num_button_0 = Button(
    text="0",
    fg = "#FFFFFF",
    activeforeground="#FFFFFF",
    compound="center",
    font=(global_font, global_font_size * -1),
    image=img_num_button,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: add_symbol(0),
    relief="flat"
)
num_button_0.place(
    x=90.6910629272461,
    y=353.0,
    width=82.92682647705078,
    height=45.0
)

op_button_plus = Button(
    text="+",
    fg = "#FFFFFF",
    activeforeground="#FFFFFF",
    compound="center",
    font=(global_font, global_font_size * -1),
    image=img_op_button,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: add_symbol("+"),
    relief="flat"
)
op_button_plus.place(
    x=262.0731506347656,
    y=212.0,
    width=82.92682647705078,
    height=45.0
)

op_button_minus = Button(
    text="-",
    fg = "#FFFFFF",
    activeforeground="#FFFFFF",
    compound="center",
    font=(global_font, global_font_size * -1),
    image=img_op_button,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: add_symbol("-"),
    relief="flat"
)
op_button_minus.place(
    x=262.0731506347656,
    y=259.0,
    width=82.92682647705078,
    height=45.0
)

op_button_mul = Button(
    text="×",
    fg = "#FFFFFF",
    activeforeground="#FFFFFF",
    compound="center",
    font=(global_font, global_font_size * -1),
    image=img_op_button,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: add_symbol("*"),
    relief="flat"
)
op_button_mul.place(
    x=262.0731506347656,
    y=306.0,
    width=82.92682647705078,
    height=45.0
)

op_button_div = Button(
    text="÷",
    fg = "#FFFFFF",
    activeforeground="#FFFFFF",
    compound="center",
    font=(global_font, global_font_size * -1),
    image=img_op_button,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: add_symbol("/"),
    relief="flat"
)
op_button_div.place(
    x=262.0731506347656,
    y=353.0,
    width=82.92682647705078,
    height=45.0
)

op_button_pow = Button(
    text="^",
    fg = "#FFFFFF",
    activeforeground="#FFFFFF",
    compound="center",
    font=(global_font, global_font_size * -1),
    image=img_num_button,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: add_symbol("**"),
    relief="flat"
)
op_button_pow.place(
    x=5.0,
    y=353.0,
    width=82.92682647705078,
    height=45.0
)

misc_button_roundopen = Button(
    text="(",
    fg = "#FFFFFF",
    activeforeground="#FFFFFF",
    compound="center",
    font=(global_font, global_font_size * -1),
    image=img_op_button,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: add_symbol("("),
    relief="flat"
)
misc_button_roundopen.place(
    x=5.0,
    y=165.0,
    width=82.92682647705078,
    height=45.0
)

misc_button_roundclose = Button(
    text=")",
    fg = "#FFFFFF",
    activeforeground="#FFFFFF",
    compound="center",
    font=(global_font, global_font_size * -1),
    image=img_op_button,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: add_symbol(")"),
    relief="flat"
)
misc_button_roundclose.place(
    x=90.6910629272461,
    y=165.0,
    width=82.92682647705078,
    height=45.0
)

misc_button_point = Button(
    text=".",
    fg = "#FFFFFF",
    activeforeground="#FFFFFF",
    compound="center",
    font=(global_font, global_font_size * -1),
    image=img_num_button,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: add_symbol("."),
    relief="flat"
)
misc_button_point.place(
    x=176.3821258544922,
    y=353.0,
    width=82.92682647705078,
    height=45.0
)

misc_button_del = Button(
    image=img_del_button,
    borderwidth=0,
    highlightthickness=0,
    command=delete_symbol,
    relief="flat"
)
misc_button_del.place(
    x=176.3821258544922,
    y=165.0,
    width=168.6178741455078,
    height=45.0
)

misc_button_res = Button(
    text="=",
    fg = "#FFFFFF",
    activeforeground="#FFFFFF",
    compound="center",
    font=(global_font, global_font_size * -1),
    image=img_res_button,
    borderwidth=0,
    highlightthickness=0,
    command=evaluate_calculation,
    relief="flat"
)
misc_button_res.place(
    x=176.3821258544922,
    y=400.0,
    width=168.6178741455078,
    height=45.0
)

misc_button_clr = Button(
    text="C",
    fg = "#FFFFFF",
    activeforeground="#FFFFFF",
    compound="center",
    font=(global_font, global_font_size * -1),
    image=img_clr_button,
    borderwidth=0,
    highlightthickness=0,
    command=clear_field,
    relief="flat"
)
misc_button_clr.place(
    x=5.0,
    y=400.0,
    width=168.6178741455078,
    height=45.0
)

misc_entry_calculation_bg = canvas.create_image(
    175.0,
    107.5,
    image=img_calculation_entry
)
misc_entry_calculation = Text(
    bd=0,
    bg="#142F44",
    fg="#FFFFFF",
    font = (global_font, 15),
    highlightthickness=0,
    wrap='word'
)
misc_entry_calculation.place(
    x=5.0,
    y=52.0,
    width=340.0,
    height=109.0
)

image_2 = canvas.create_image(
    540.0,
    121.0,
    image=img_res_button_hover
)

image_3 = canvas.create_image(
    539.0,
    168.0,
    image=img_res_button_press
)

image_4 = canvas.create_image(
    540.0,
    215.0,
    image=img_clr_button_hover
)

image_5 = canvas.create_image(
    540.0,
    262.0,
    image=img_clr_button_press
)

image_6 = canvas.create_image(
    540.0,
    74.0,
    image=img_del_button_press
)

image_7 = canvas.create_image(
    540.0,
    27.0,
    image=img_del_button_hover
)

image_8 = canvas.create_image(
    411.0,
    27.0,
    image=img_num_button_hover
)

window.resizable(False, False)
window.mainloop()